/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Dark theme tokens
        "dark-bg": "#07151f",
        "dark-surface": "#07151f",
        "dark-surface-low": "#0f1d28",
        "dark-surface-lowest": "#030f1a",
        "dark-surface-container": "#13212c",
        "dark-surface-high": "#1e2b37",
        "dark-surface-highest": "#293642",
        "dark-surface-bright": "#2d3b47",
        "dark-primary": "#42dec3",
        "dark-primary-container": "#00c2a8",
        "dark-secondary": "#68dba9",
        "dark-secondary-container": "#25a475",
        "dark-tertiary": "#7fd1ff",
        "dark-tertiary-container": "#30b8f3",
        "dark-error": "#ffb4ab",
        "dark-error-container": "#93000a",
        "dark-on-surface": "#d6e4f4",
        "dark-on-surface-variant": "#bbcac4",

        // Light theme tokens
        "light-bg": "#f4f8fb",
        "light-surface": "#faf8ff",
        "light-surface-low": "#f2f3ff",
        "light-surface-lowest": "#ffffff",
        "light-surface-container": "#eaedff",
        "light-surface-high": "#e2e7ff",
        "light-surface-highest": "#dae2fd",
        "light-primary": "#00685f",
        "light-primary-container": "#008378",
        "light-secondary": "#515f74",
        "light-tertiary": "#006948",
        "light-error": "#ba1a1a",
        "light-error-container": "#ffdad6",
        "light-on-surface": "#131b2e",
        "light-on-surface-variant": "#3d4947",

        // Semantic tokens (dynamic via CSS variables or defaults)
        background: "var(--color-background, #07151f)",
        surface: "var(--color-surface, #07151f)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #030f1a)",
        "surface-container-low": "var(--color-surface-container-low, #0f1d28)",
        "surface-container": "var(--color-surface-container, #13212c)",
        "surface-container-high": "var(--color-surface-container-high, #1e2b37)",
        "surface-container-highest": "var(--color-surface-container-highest, #293642)",
        "surface-bright": "var(--color-surface-bright, #2d3b47)",
        "on-surface": "var(--color-on-surface, #d6e4f4)",
        "on-surface-variant": "var(--color-on-surface-variant, #bbcac4)",
        primary: "var(--color-primary, #42dec3)",
        "primary-container": "var(--color-primary-container, #00c2a8)",
        "on-primary": "var(--color-on-primary, #00382f)",
        "on-primary-container": "var(--color-on-primary-container, #00493e)",
        secondary: "var(--color-secondary, #68dba9)",
        "secondary-container": "var(--color-secondary-container, #25a475)",
        "on-secondary": "var(--color-on-secondary, #003825)",
        tertiary: "var(--color-tertiary, #7fd1ff)",
        "tertiary-container": "var(--color-tertiary-container, #30b8f3)",
        error: "var(--color-error, #ffb4ab)",
        "error-container": "var(--color-error-container, #93000a)",
        "on-error": "var(--color-on-error, #690005)",
        outline: "var(--color-outline, #85948f)",
        "outline-variant": "var(--color-outline-variant, #3c4a46)",
      },
      spacing: {
        "space-xxs": "4px",
        "space-xs": "8px",
        "space-sm": "12px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "32px",
        "space-2xl": "48px",
        "space-3xl": "64px",
        "grid-gutter": "32px",
        "card-padding-compact": "20px",
        "card-padding-default": "28px",
        "card-padding-spacious": "36px",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Display",
          "SF Pro Text",
          "Plus Jakarta Sans",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "SF Mono", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-numeric": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
